[colors.primary]
  # Default colors
    background = '0xdbd6d1'
    foreground = '0x433b32'

  # Normal colors
[colors.normal]
    black =   '0x16130f'
    red =     '0x826d57'
    green =   '0x57826d'
    yellow =  '0x6d8257'
    blue =    '0x6d5782'
    magenta = '0x82576d'
    cyan =    '0x576d82'
    white =   '0xa39a90'

  # Bright colors
[colors.bright]
    black =   '0x5a5047'
    red =     '0x826d57'
    green =   '0x57826d'
    yellow =  '0x6d8257'
    blue =    '0x6d5782'
    magenta = '0x82576d'
    cyan =    '0x576d82'
    white =   '0xdbd6d1'
