[colors.primary]
    background = '0x0f0f0f'
    foreground = '0xf0f0f0'

[colors.normal]
    black =   '0x262626'
    red =     '0xac8a8c'
    green =   '0x8aac8b'
    yellow =  '0xaca98a'
    blue =    '0x8f8aac'
    magenta = '0xac8aac'
    cyan =    '0x8aabac'
    white =   '0xe7e7e7'

[colors.bright]
    black =   '0x4c4c4c'
    red =     '0xc49ea0'
    green =   '0x9ec49f'
    yellow =  '0xc4c19e'
    blue =    '0xa39ec4'
    magenta = '0xc49ec4'
    cyan =    '0x9ec3c4'
    white =   '0xf5f5f5'
