# Colors (One Half Dark)
[colors.primary]
    background = '0x282c34'
    foreground = '0xdcdfe4'

[colors.normal]
    black = '0x282c34'
    red = '0xe06c75'
    green = '0x98c379'
    yellow = '0xe5c07b'
    blue = '0x61afef'
    magenta = '0xc678dd'
    cyan = '0x56b6c2'
    white = '0xdcdfe4'

[colors.bright]
    black = '0x282c34'
    red = '0xe06c75'
    green = '0x98c379'
    yellow = '0xe5c07b'
    blue = '0x61afef'
    magenta = '0xc678dd'
    cyan = '0x56b6c2'
    white = '0xdcdfe4'
